#!/usr/bin/python3

import argparse
import docker
import system_updates

parser = argparse.ArgumentParser(description='manage vserver tasks')
parser.add_argument("action", type=str, metavar="ACTION")
parser.add_argument("options", type=str, metavar="OPTIONS", nargs='*')

args = parser.parse_args()


#Update all docker images
if args.action == "docker:update-images":
    docker.update_images()

if args.action == "system-updates:check":
    system_updates.check()

if args.action == "system-updates:upgrade":
    system_udates.upgrade()